server.port=8085
spring.application.name=enrollment-service


spring.datasource.url=jdbc:mysql://localhost:3306/enrollment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=learning_user
spring.datasource.password=learning_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


services.student.url=http://localhost:8082
services.course.url=http://localhost:8083
services.certificate.url=http://localhost:8087


logging.level.com.onlinelearning.enrollment=DEBUG
